# grace fingerprint: xe8k48177na9rg52syvbt9g0gzbp3afe
identity: ./grace-identity.asc
in_routes:
  main_udp:
    listen: 0.0.0.0:19999
    protocol: obfsudp
    secret: yRWA0lz3AL
out_routes:
  heidi:
    connect: 200.64.1.10:19999
    cookie: 279457cda54bcbf72dc10349c77bd84a127e103502ceb7b9721709ce670ee81c
    fingerprint: w4a2az2ew1mp9jnkr6rz13vy9p0sbgt3
    protocol: obfsudp
state_cache: ./grace-state-cache.db
