# oliver fingerprint: wp036avqcrcjenmb89jg38qps4snvjw9
identity: ./oliver-identity.asc
in_routes:
  main_udp:
    listen: 0.0.0.0:19999
    protocol: obfsudp
    secret: Cu62f4NUtq
out_routes:
  karen:
    connect: 200.64.1.3:19999
    cookie: 169cd7c7f0d72e1a76e755a87eb0579b77d1c7280770db2d292da3be9d20ad76
    fingerprint: kgcyfshe305fj6yagy7ep45trfp31r0y
    protocol: obfsudp
state_cache: ./oliver-state-cache.db
