# alice fingerprint: 8qqn4wr0t8y4xc71qxw6hp0xekansbs4
identity: ./alice-identity.asc
in_routes:
  main_udp:
    listen: 0.0.0.0:19999
    protocol: obfsudp
    secret: wSehwx7FXY
out_routes:
  bob:
    connect: 1.0.0.2:19999
    cookie: d6fea441c142d01784b258995b38c4db9ffc627e5803a2b2b0ac39a735e33a1f
    fingerprint: md244fewrdkr5vyra0akh220hn0kxavk
    protocol: obfsudp
state_cache: ./alice-state-cache.db
