# oliver fingerprint: mnzkr7cbt3z9emfb1pqjbv38afhxethd
identity: ./oliver-identity.asc
in_routes:
  main_udp:
    listen: 0.0.0.0:19999
    protocol: obfsudp
    secret: zF1JrOmqmO
out_routes:
  karen:
    connect: 200.64.1.6:19999
    cookie: 78d158ffb9a795258b63cc7d0ceeb5ba48435ef77e5bf36a8ba3b324a80cd76b
    fingerprint: 51cs86ne551nsk0kp45zg658mfaegz73
    protocol: obfsudp
state_cache: ./oliver-state-cache.db
