# alice fingerprint: qtjp4b0b0524m0cjd8t9hsepr41ex6se
identity: ./alice-identity.asc
in_routes:
  main_udp:
    listen: 0.0.0.0:19999
    protocol: obfsudp
    secret: bdJ5HJb5FC
out_routes:
  bob:
    connect: 200.64.1.16:19999
    cookie: 29ee0faeb08076b31b67377b0add87c231d3718e4a11f4df8194b42387f8ce55
    fingerprint: bavm5gf3fkzwzcz9rnbqtqmca2qtgswv
    protocol: obfsudp
state_cache: ./alice-state-cache.db
