# mallory fingerprint: 416qsccvqpp0rzymbsyh71kfazx0xk9e
identity: ./mallory-identity.asc
in_routes:
  main_udp:
    listen: 0.0.0.0:19999
    protocol: obfsudp
    secret: ScNoZznlgR
out_routes:
  niaj:
    connect: 200.64.1.9:19999
    cookie: d93670ba25f0dd70621708cfd4cbfc5a72481206f6e27bca33f47911ee5e8f71
    fingerprint: 8nptmhcb0wj2wncsbztwbcj037daswcq
    protocol: obfsudp
state_cache: ./mallory-state-cache.db
