# quetzal fingerprint: rg6p8dbjbqvapb9r72xfq5p1hf2xvzg9
identity: ./quetzal-identity.asc
in_routes:
  main_udp:
    listen: 0.0.0.0:19999
    protocol: obfsudp
    secret: xNzcTKiPmJ
out_routes:
  rupert:
    connect: 200.64.1.12:19999
    cookie: 7285001d7e25b97f0f4a6a0f9ffe1262e1f5d677f07ce3aff93b03b27f9f6d5c
    fingerprint: x7vfb355kgf5qzn7j77xcpwnafendg58
    protocol: obfsudp
state_cache: ./quetzal-state-cache.db
