identity: ./client-identity.asc
state_cache:  ./client-state-cache.db

out_routes:
  neighbor:
    fingerprint: 489HfqWo5Uivgm4xdFy7s2eDMhwW
    protocol: obfsudp
    connect: 1.2.3.4:19999
    cookie: bb27ead798b27ec3384ac2cf2f374a17c02bfce420b19e8b2c5a8f898fd6384d
