# fingerprint: 5mnn8aejs0ac0q1hqhkv6wrr2ygv16x3
identity_seed: bob
state_cache: bob_cache.db
control_listen: 127.0.0.1:22222

out_routes:
  alice:
    fingerprint: 7wrkhwar5kj3hybwaf9pe996eydzc969
    protocol: obfsudp
    connect: 127.0.0.1:19999
    cookie: bb27ead798b27ec3384ac2cf2f374a17c02bfce420b19e8b2c5a8f898fd6384d

# server config
havens:
  # fingerprint: pm3atrnq6awfp96qrjg5rmxp39d1bqfh
  - identity_seed: TCP_haven
    rendezvous: 0k28pjf5qa8nwbt7cn8138xetxdknhz3
    handler:
      type: tcp_forward
      from_dock: 69421
      to_port: 8888