# fingerprint: 0k28pjf5qa8nwbt7cn8138xetxdknhz3
identity_seed: rob
state_cache: rob_cache.db
control_listen: 127.0.0.1:33333

out_routes:
  alice:
    fingerprint: 7wrkhwar5kj3hybwaf9pe996eydzc969
    protocol: obfsudp
    connect: 200.64.1.1:19999
    cookie: bb27ead798b27ec3384ac2cf2f374a17c02bfce420b19e8b2c5a8f898fd6384d
