# charlie fingerprint: 40xfwvywhag8sgen33qpr4rvzynxt5vc
identity: ./charlie-identity.asc
in_routes:
  main_udp:
    listen: 0.0.0.0:19999
    protocol: obfsudp
    secret: bHEaPPIru4

state_cache: ./charlie-state-cache.db
