# wren fingerprint: 2efm7f61x808ezad4bkfgrr4c03s4624
identity_seed: cinnamon-devote-entry-trick-lottery-service-impact-inhale-laugh-toward-bounce-critic
in_routes:
  main_udp:
    listen: 0.0.0.0:12006
    protocol: obfsudp
    secret: sample-confirm-common-milk-slam-hill-below-cook-stand-wrap-tomorrow-east
out_routes:
  fowl:
    connect: 200.64.1.14:12026
    cookie: 6ed1cc81790ea010b0a529b12a08c14c7eb6c61e6ff439f24c29bfd26ea04d28
    fingerprint: xtmz9eyfc4tgpvpessjx5762s4fzjnvb
    protocol: obfsudp
  pug:
    connect: 200.64.1.8:12014
    cookie: 0fa6d7dbb2b2223e8feb92c8f341e9230d051d989f2d3bf28fd297894616b478
    fingerprint: p56n010gbdf9aqxpzjjmx59hhr4gst8b
    protocol: obfsudp
