# phoenix fingerprint: hgqmxycs7s75d8gzm4w1a4v7nb98nb3k
identity_seed: east-dress-oyster-matrix-census-grace-cruise-tissue-busy-pull-warrior-pledge
in_routes:
  main_udp:
    listen: 0.0.0.0:12004
    protocol: obfsudp
    secret: caution-coil-razor-cake-cargo-nuclear-reflect-pear-winter-swamp-man-version
out_routes:
  moth:
    connect: 200.64.1.11:12020
    cookie: e79180b93df166ddd9db693ceec84678797c561cd5e5b93f9660b7ea54bd046f
    fingerprint: 6c8bghanhkmyzamxqyz9n8edm9b3b1vv
    protocol: obfsudp
  pug:
    connect: 200.64.1.8:12014
    cookie: 0fa6d7dbb2b2223e8feb92c8f341e9230d051d989f2d3bf28fd297894616b478
    fingerprint: p56n010gbdf9aqxpzjjmx59hhr4gst8b
    protocol: obfsudp
  sawfish:
    connect: 200.64.1.9:12016
    cookie: 94f52a95e26f6925a51103777be9074f51e726e4ffd9c475f4929d1f039b153b
    fingerprint: 0a6r82xs3g7xephae89bt673qznm5ycq
    protocol: obfsudp
