# dory fingerprint: w742x18w872v2gd9fgd5bpxd1990g7e2
identity_seed: hire-scissors-rookie-combine-front-strike-erase-proud-there-more-velvet-vivid
in_routes:
  main_udp:
    listen: 0.0.0.0:12034
    protocol: obfsudp
    secret: nut-dumb-rent-industry-tool-name-empower-human-pitch-labor-denial-journey
out_routes:
  burro:
    connect: 200.64.1.6:12010
    cookie: fc760624957edf838ee9387bff13d67b6ab5c30f6507ffe008a5d59a85be367d
    fingerprint: fnef5zpfjbpm7pp5pvjgxrs39z2tpg4y
    protocol: obfsudp
  parakeet:
    connect: 200.64.1.16:12030
    cookie: 9ead3e46c05b5f36c662afdb9fbd0ab3d9a9e5a562703f3f6852db0e3ac52f1a
    fingerprint: h133nnen7zx9kny8sdp47p9mzpz0pcg6
    protocol: obfsudp
  pug:
    connect: 200.64.1.8:12014
    cookie: 0fa6d7dbb2b2223e8feb92c8f341e9230d051d989f2d3bf28fd297894616b478
    fingerprint: p56n010gbdf9aqxpzjjmx59hhr4gst8b
    protocol: obfsudp
