identity: ./bob-identity.asc
state_cache: ./bob-state-cache.db
# control_listen: 127.0.0.1:11111

in_routes:
  main_udp:
    protocol: obfsudp
    listen: 0.0.0.0:56789
    secret: correct horse battery staple

out_routes:
  # charlie
  neighbor:
    fingerprint: e86p9brr5eqvertwqmafz2nxb36sajqy
    protocol: obfsudp
    connect: 2.3.4.5:6789
    cookie: 626acdd44321af0ccaa710f1b543e8550772d0354020617ff75cc6d82934a532
