general:
  stop_time: 300 sec
  seed: 1
  parallelism: 0
  bootstrap_end_time: 0 sec
  log_level: info
  heartbeat_interval: 1 sec
  data_directory: shadow.data
  template_directory: ./configs/
  progress: false
  model_unblocked_syscall_latency: false
network:
  graph:
    type: 1_gbit_switch
  use_shortest_path: true
experimental:
  use_sched_fifo: false
  use_syscall_counters: true
  use_object_counters: true
  use_preload_libc: true
  use_preload_openssl_rng: true
  use_preload_openssl_crypto: false
  use_memory_manager: false
  use_cpu_pinning: true
  use_worker_spinning: true
  runahead: 1 ms
  use_dynamic_runahead: false
  socket_send_buffer: 131072 B
  socket_send_autotune: true
  socket_recv_buffer: 174760 B
  socket_recv_autotune: true
  interface_qdisc: fifo
  host_heartbeat_log_level: info
  host_heartbeat_log_info:
  - node
  host_heartbeat_interval: 1 sec
  strace_logging_mode: off
  max_unapplied_cpu_latency: 1 μs
  unblocked_syscall_latency: 1 μs
  unblocked_vdso_latency: 10 ns
  scheduler: thread-per-core
  log_errors_to_tty: true
  use_new_tcp: false
hosts:
  alice:
    network_node_id: 0
    processes:
    - path: earendil
      args: daemon --config alice-cfg.yaml
      environment: {}
      start_time: 70 sec
      shutdown_time: null
      shutdown_signal: SIGTERM
      expected_final_state: running
    - path: earendil
      args: control send-message --destination 2bACMbANy7t7CMgwT2EhcidyFADK --message helloworld
      environment: {}
      start_time: 200 sec
      shutdown_time: null
      shutdown_signal: SIGTERM
      expected_final_state:
        exited: 0
    ip_addr: 3.4.5.6
    bandwidth_down: null
    bandwidth_up: null
    host_options:
      log_level: null
      pcap_enabled: false
      pcap_capture_size: 65535 B
  bob:
    network_node_id: 0
    processes:
    - path: earendil
      args: daemon --config bob-cfg.yaml
      environment: {}
      start_time: 0 sec
      shutdown_time: null
      shutdown_signal: SIGTERM
      expected_final_state: running
    ip_addr: 1.2.3.4
    bandwidth_down: null
    bandwidth_up: null
    host_options:
      log_level: null
      pcap_enabled: false
      pcap_capture_size: 65535 B
  charlie:
    network_node_id: 0
    processes:
    - path: earendil
      args: daemon --config charlie-cfg.yaml
      environment: {}
      start_time: 0 sec
      shutdown_time: null
      shutdown_signal: SIGTERM
      expected_final_state: running
    - path: earendil
      args: control recv-message
      environment: {}
      start_time: 260 sec
      shutdown_time: null
      shutdown_signal: SIGTERM
      expected_final_state:
        exited: 0
    ip_addr: 2.3.4.5
    bandwidth_down: null
    bandwidth_up: null
    host_options:
      log_level: null
      pcap_enabled: false
      pcap_capture_size: 65535 B
