# bob fingerprint: bavm5gf3fkzwzcz9rnbqtqmca2qtgswv
identity: ./bob-identity.asc
in_routes:
  main_udp:
    listen: 0.0.0.0:19999
    protocol: obfsudp
    secret: SonPCh3N2k
out_routes:
  charlie:
    connect: 200.64.1.7:19999
    cookie: be7a3d4aebc930aba38b09c20d7e1e485eca48004b3b9e6214554642fbe7636a
    fingerprint: y16fydts104wstmj0fr9fm4p05xry51b
    protocol: obfsudp
state_cache: ./bob-state-cache.db
