# laura fingerprint: 73kfays1knf9rajgcxxma7cq0rnp05t8
identity: ./laura-identity.asc
in_routes:
  main_udp:
    listen: 0.0.0.0:19999
    protocol: obfsudp
    secret: XJmaLlBvXb
out_routes:
  mark:
    connect: 200.64.1.17:19999
    cookie: 1b8bdb5ce9497d5e4751b62e4ea295fc26895c5d6ae0fabf6873252072cd3f59
    fingerprint: apys3gvs65w4d8t3mcqk3jfh7r9ppwfa
    protocol: obfsudp
  nora:
    connect: 200.64.1.8:19999
    cookie: 68d9ee65f38a5194d066f2f429f076b8b10f7325485a6e37071ec06be71e1841
    fingerprint: ebcmq5nf96bf3r2916ca1ydj1v7za18p
    protocol: obfsudp
state_cache: ./laura-state-cache.db
