# mark fingerprint: apys3gvs65w4d8t3mcqk3jfh7r9ppwfa
identity: ./mark-identity.asc
in_routes:
  main_udp:
    listen: 0.0.0.0:19999
    protocol: obfsudp
    secret: TVb0kfPKo8
out_routes:
  nora:
    connect: 200.64.1.8:19999
    cookie: 68d9ee65f38a5194d066f2f429f076b8b10f7325485a6e37071ec06be71e1841
    fingerprint: ebcmq5nf96bf3r2916ca1ydj1v7za18p
    protocol: obfsudp
state_cache: ./mark-state-cache.db
