# rob fingerprint: d3ngse8f3gk3rrhax8xrcvfdp6grgckj
identity: ./rob-identity.asc
in_routes:
  main_udp:
    listen: 0.0.0.0:19999
    protocol: obfsudp
    secret: YX1U8mc6Lp
out_routes:
  bob:
    connect: 200.64.1.2:19999
    cookie: 3d602f767bab55c64f83fffd98c93655a15b9c8dcf54a4fd36823de6ea0d1f49
    fingerprint: pqrzkhgy69m9km2nn9qj1df0788zh9k7
    protocol: obfsudp
state_cache: ./rob-state-cache.db
