# kyle fingerprint: vpjg27nremn2fjt0jk9419mfxk60kc7f
identity: ./kyle-identity.asc
in_routes:
  main_udp:
    listen: 0.0.0.0:19999
    protocol: obfsudp
    secret: JagVOrLFHr
out_routes:
  liam:
    connect: 200.64.1.14:19999
    cookie: bd74172c037fe85052c1327445acc3bc5cab15621a4423a8b4fef38fde14e04d
    fingerprint: 765dd8qyvqgcb1kjmtyk2p4fvtsxvxrg
    protocol: obfsudp
state_cache: ./kyle-state-cache.db
