# hyena fingerprint: 19zfwkfyy885dhm0nthz5rvwwkv62pj4
identity_seed: leg-circle-spring-clarify-list-parade-alter-faculty-glide-water-uncover-picture
in_routes:
  main_udp:
    listen: 0.0.0.0:12000
    protocol: obfsudp
    secret: organ-direct-pupil-eternal-erosion-cute-govern-hair-case-trial-blast-lawsuit
out_routes:
  honeybee:
    connect: 200.64.1.10:12018
    cookie: ab1822ec6e0b2696462290bc96eae6c685f5cf345a2bc502e833b37037e50c61
    fingerprint: s0x2aww6w0qaqtfawvdmtgjhqssqs15z
    protocol: obfsudp
  parakeet:
    connect: 200.64.1.16:12030
    cookie: 9ead3e46c05b5f36c662afdb9fbd0ab3d9a9e5a562703f3f6852db0e3ac52f1a
    fingerprint: h133nnen7zx9kny8sdp47p9mzpz0pcg6
    protocol: obfsudp
  pug:
    connect: 200.64.1.8:12014
    cookie: 0fa6d7dbb2b2223e8feb92c8f341e9230d051d989f2d3bf28fd297894616b478
    fingerprint: p56n010gbdf9aqxpzjjmx59hhr4gst8b
    protocol: obfsudp
