identity: ./alice-identity.asc
state_cache:  ./alice-state-cache.db

in_routes:
  # arbitrary names, used for diagnositics and logging
  main_udp:
    protocol: obfsudp
    listen: 0.0.0.0:17777
    secret: correct horse phone staple


out_routes:
  # bob
  neighbor:
    fingerprint: w0pj999ezrc36spw5zz88nn79z9h7mss
    protocol: obfsudp
    connect: 1.2.3.4:19999
    cookie: bb27ead798b27ec3384ac2cf2f374a17c02bfce420b19e8b2c5a8f898fd6384d
