# melanie fingerprint: njsh4h0gp2r4bhp1wjvfcjyd4xyzhpd5
identity: ./melanie-identity.asc
in_routes:
  main_udp:
    listen: 0.0.0.0:19999
    protocol: obfsudp
    secret: VTE0NnTmdy
out_routes:
  carol:
    connect: 200.64.1.1:19999
    cookie: be0497db82f271b23b20c71252ec7fd19254c2ea8fdf2b00274b1da85e141b76
    fingerprint: xp9a70cw4vbcqknypn45ah2v7exq2wdj
    protocol: obfsudp
  nathan:
    connect: 200.64.1.5:19999
    cookie: ee2e0cc7ebc84dd9410222102b4580f6a824b6f1a11ec7bede59d7b22253d366
    fingerprint: kpxd728sem0awmsxnj22bztt1z2dm8hc
    protocol: obfsudp
  oliver:
    connect: 200.64.1.4:19999
    cookie: 86991db100a477bf08c0df9950de18a79e044fad43b1d4f140a070bebc51c06c
    fingerprint: mnzkr7cbt3z9emfb1pqjbv38afhxethd
    protocol: obfsudp
state_cache: ./melanie-state-cache.db
