# niaj fingerprint: 8nptmhcb0wj2wncsbztwbcj037daswcq
identity: ./niaj-identity.asc
in_routes:
  main_udp:
    listen: 0.0.0.0:19999
    protocol: obfsudp
    secret: r7SkjcnBKf
out_routes:
  olivia:
    connect: 200.64.1.1:19999
    cookie: 5c2083e176c5343d89b2ca5f7490c9abf16071cf75ee845b71f01c98d4e1251c
    fingerprint: 4xt4m5meyeaxq9qnc9nfeaf8dk90xv5k
    protocol: obfsudp
state_cache: ./niaj-state-cache.db
