identity: ./relay-identity.asc
state_cache: ./relay-state-cache.db
control_listen: 127.0.0.1:11111

in_routes:
  # arbitrary names, used for diagnositics and logging
  main_udp:
    protocol: obfsudp
    listen: 0.0.0.0:19999
    secret: correct horse battery staple
